import requests
import json
import uuid

BASE_URL = "http://127.0.0.1:8000/api/v1"

def print_banner(title):
    print("\n" + "="*80)
    print(f"=== {title} ===")
    print("="*80)

def test_unified_ai_platform():
    print_banner("SMARTHIRE UNIFIED AI RECRUITMENT PLATFORM VERIFICATION")

    # 1. Candidate Authentication & Setup
    cand_email = f"unified_candidate_{uuid.uuid4().hex[:4]}@smarthire.ai"
    reg_c = requests.post(f"{BASE_URL}/auth/register", json={
        "email": cand_email,
        "password": "Password123!",
        "full_name": "Senior Software Architect Candidate",
        "role": "candidate"
    })
    cand_token = reg_c.json().get("access_token") or reg_c.json().get("tokens", {}).get("access_token")
    c_headers = {"Authorization": f"Bearer {cand_token}"}
    print(f"[OK] Candidate Registered & Authenticated: {cand_email}")

    # 2. Recruiter Authentication & Job Requisition Posting
    rec_email = f"unified_recruiter_{uuid.uuid4().hex[:4]}@smarthire.ai"
    reg_r = requests.post(f"{BASE_URL}/auth/register", json={
        "email": rec_email,
        "password": "Password123!",
        "full_name": "Chief Talent Partner",
        "role": "recruiter"
    })
    rec_token = reg_r.json().get("access_token") or reg_r.json().get("tokens", {}).get("access_token")
    r_headers = {"Authorization": f"Bearer {rec_token}"}
    print(f"[OK] Recruiter Registered & Authenticated: {rec_email}")

    job_res = requests.post(f"{BASE_URL}/jobs/create", json={
        "title": "Principal AI & Systems Engineer",
        "company_name": "Unified Enterprise Corp",
        "department": "Engineering",
        "employment_type": "Full-Time",
        "work_mode": "Remote",
        "experience_required": "5+ Years",
        "location": "San Francisco, CA",
        "salary_range": "$180,000 - $240,000",
        "description": "Lead design and deployment of distributed AI infrastructure using Python, FastAPI, PostgreSQL, and React.",
        "required_skills": ["Python", "FastAPI", "PostgreSQL", "React", "Docker"],
        "openings": 2
    }, headers=r_headers)
    job_data = job_res.json()
    job_id = job_data["id"] if "id" in job_data else job_data.get("job", {}).get("id")
    print(f"[OK] Recruiter Requisition Posted: Job ID={job_id}")

    # 3. UNIFIED ENGINE MODULE 1: Candidate Practice Hub - AI Mock Assessment
    print("\n--- [MODULE 1] AI Practice Hub: Candidate Practice Assessment ---")
    start_assess_res = requests.post(f"{BASE_URL}/aptitude/start", json={
        "title": "Practice Hub Tech & Reasoning Assessment",
        "topics": ["Quantitative Aptitude", "React", "PostgreSQL & Indexing"],
        "difficulty": "Medium",
        "question_count": 5,
        "duration_minutes": 10,
        "passing_score": 70.0,
        "negative_marking": 0.25,
        "proctoring_enabled": True
    }, headers=c_headers)
    assert start_assess_res.status_code == 200, f"Start assessment failed: {start_assess_res.text}"
    sess_data = start_assess_res.json()
    assess_session_id = sess_data["session_id"]
    print(f"[OK] Practice Assessment Session Created: ID={assess_session_id}")

    # Fetch MCQs generated by Gemini
    qs_res = requests.get(f"{BASE_URL}/aptitude/session/{assess_session_id}/questions", headers=c_headers)
    assert qs_res.status_code == 200, f"Fetch MCQs failed: {qs_res.text}"
    questions = qs_res.json()
    print(f"[OK] Gemini Generated {len(questions)} MCQs:")
    for idx, q in enumerate(questions, start=1):
        print(f"  Q{idx} [{q['category']} - {q['topic']}]: {q['question_text']}")

    # Submit Answers with Proctoring Violation
    answers = [
        {"question_id": questions[0]["id"], "selected_option": 1, "time_taken_seconds": 25},
        {"question_id": questions[1]["id"], "selected_option": 0, "time_taken_seconds": 30},
        {"question_id": questions[2]["id"], "selected_option": None, "time_taken_seconds": 10}, # Skipped
    ]
    sub_res = requests.post(f"{BASE_URL}/aptitude/session/{assess_session_id}/submit", json={
        "answers": answers,
        "proctoring_violations": 1
    }, headers=c_headers)
    assert sub_res.status_code == 200, f"Submit assessment failed: {sub_res.text}"
    print(f"[OK] Practice Assessment Submitted & Evaluated (Proctoring Violations Logged: 1)")

    # Fetch Full Assessment Report & Explanations
    rep_res = requests.get(f"{BASE_URL}/aptitude/session/{assess_session_id}/result", headers=c_headers)
    assert rep_res.status_code == 200, f"Fetch assessment result failed: {rep_res.text}"
    report = rep_res.json()
    print(f"[OK] Full Assessment Report Generated:")
    print(f"  - Overall Score: {report['overall_score']}% | Recommendation: {report['hiring_recommendation']}")
    print(f"  - Correct: {report['total_correct']} | Wrong: {report['total_wrong']} | Skipped: {report['total_skipped']}")
    print(f"  - Weak Areas: {report['weak_areas']} | Strong Areas: {report['strong_areas']}")

    # 4. UNIFIED ENGINE MODULE 2: Candidate Practice Hub - AI Mock Interview
    print("\n--- [MODULE 2] AI Practice Hub: Candidate Practice Interview ---")
    mock_int_res = requests.post(f"{BASE_URL}/interview/start", json={
        "role_target": "Principal AI Engineer",
        "round_type": "Technical",
        "difficulty": "Hard",
        "duration_minutes": 15
    }, headers=c_headers)
    assert mock_int_res.status_code == 200, f"Start mock interview failed: {mock_int_res.text}"
    mock_int_data = mock_int_res.json()
    int_session_id = mock_int_data["session_id"]
    print(f"[OK] AI Mock Interview Started: Session ID={int_session_id}")
    print(f"[Q1]: {mock_int_data['first_question']['question_text']}")

    # 5. UNIFIED ENGINE MODULE 3: Recruiter Online Assessment Manager
    print("\n--- [MODULE 3] Recruiter Online Assessment Configuration ---")
    rec_config_res = requests.post(f"{BASE_URL}/aptitude/start", json={
        "title": "Enterprise Screening Test - Principal AI Engineer",
        "topics": ["DBMS", "System Design", "Python", "FastAPI"],
        "difficulty": "Hard",
        "question_count": 10,
        "duration_minutes": 30,
        "passing_score": 80.0,
        "negative_marking": 0.25,
        "proctoring_enabled": True,
        "is_recruiter_configured": True,
        "job_id": job_id
    }, headers=r_headers)
    assert rec_config_res.status_code == 200, f"Recruiter config assessment failed: {rec_config_res.text}"
    rec_sess_id = rec_config_res.json()["session_id"]
    print(f"[OK] Recruiter Online Assessment Published for Job ID={job_id} | Session ID={rec_sess_id}")

    # 6. UNIFIED ENGINE MODULE 4: Candidate Applications & 11-Stage Pipeline Progress
    print("\n--- [MODULE 4] Candidate Applications & 11-Stage Pipeline Status ---")
    # Candidate uploads resume & applies to job
    files = {
        "file": ("architect_resume.pdf", b"%PDF-1.4 Principal AI Engineer Python FastAPI PostgreSQL React Docker System Design", "application/pdf")
    }
    r_up = requests.post(f"{BASE_URL}/resume/upload", files=files, headers=c_headers)
    res_id = r_up.json().get("resume_id")

    apply_res = requests.post(f"{BASE_URL}/jobs/{job_id}/apply", json={
        "resume_id": res_id,
        "cover_letter": "Excited to lead distributed AI infrastructure at Unified Enterprise."
    }, headers=c_headers)
    assert apply_res.status_code == 200, f"Apply job failed: {apply_res.text}"
    app_id = apply_res.json()["application_id"]
    print(f"[OK] Candidate Applied: Application ID={app_id}")

    # Fetch Candidate Applications List & Verify Stage Status Timeline
    my_apps_res = requests.get(f"{BASE_URL}/jobs/my-applications", headers=c_headers)
    assert my_apps_res.status_code == 200, f"Fetch my applications failed: {my_apps_res.text}"
    apps_list = my_apps_res.json()
    print(f"[OK] Candidate Applications Returned ({len(apps_list)} Application Records):")
    for app in apps_list:
        print(f"  - Job: {app['job_title']} | ATS Match: {app['ats_score']}% | Pipeline Status: '{app['status']}'")

    print("\n" + "="*80)
    print("=== PASS - SMARTHIRE UNIFIED AI RECRUITMENT PLATFORM 100% VERIFIED! ===")
    print("="*80)

if __name__ == "__main__":
    test_unified_ai_platform()
