import hashlib
import json
import re

import pytest
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy import select

from app.api.v1.aptitude import StartAssessmentRequest
from app.core.db import Base
from app.models.domain import AssessmentQuestionHistory, Candidate, User
from app.services.ai_engine import ai_engine
from app.services.assessment_service import AssessmentService


@pytest.mark.parametrize("count", [10, 20, 30, 40, 50, 75, 100])
def test_supported_question_counts(count):
    assert StartAssessmentRequest(question_count=count).question_count == count


def test_duration_bounds_and_custom_duration():
    assert StartAssessmentRequest(duration_minutes=73).duration_minutes == 73
    with pytest.raises(ValueError):
        StartAssessmentRequest(duration_minutes=4)
    with pytest.raises(ValueError):
        StartAssessmentRequest(duration_minutes=181)


@pytest.mark.asyncio
async def test_three_attempts_have_no_candidate_question_overlap(monkeypatch):
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    counter = 0

    async def generated_gemini(prompt, **_kwargs):
        nonlocal counter
        count = int(re.search(r"Generate exactly (\d+)", prompt).group(1))
        topic = re.search(r"Topic: (.+)", prompt).group(1).strip()
        questions = []
        for _ in range(count):
            counter += 1
            token = hashlib.sha256(f"generated-question-{counter}".encode()).hexdigest()
            questions.append({
                "category": topic,
                "topic": topic,
                "question_text": f"React {token}",
                "code_snippet": None,
                "options": ["A", "B", "C", "D"],
                "correct_option": counter % 4,
                "explanation": f"Explanation for unique scenario {counter}.",
            })
        return json.dumps(questions)

    monkeypatch.setattr(ai_engine, "_call_gemini_with_fallback", generated_gemini)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    try:
        async with session_factory() as db:
            user = User(email="assessment-engine-test@example.com", password_hash="test", full_name="Test Candidate")
            db.add(user)
            await db.commit()
            candidate = Candidate(user_id=user.id)
            db.add(candidate)
            await db.commit()

            attempt_texts = []
            for _ in range(3):
                assessment = await AssessmentService.create_assessment_session(
                    db, candidate.id, topics=["React"], question_count=20, duration_minutes=30,
                )
                questions = await AssessmentService.generate_questions_for_session(db, assessment.id)
                assert len(questions) == 20
                attempt_texts.append([question.question_text for question in questions])

            history = (await db.execute(select(AssessmentQuestionHistory))).scalars().all()
            assert len(history) == 60
            for left in range(3):
                for right in range(left + 1, 3):
                    overlap = sum(
                        AssessmentService.calculate_text_similarity(one, two) >= 0.70
                        for one in attempt_texts[left] for two in attempt_texts[right]
                    )
                    assert overlap == 0
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_one_hundred_question_assessment_is_batched(monkeypatch):
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    batch_calls = 0

    async def generated_gemini(prompt, **_kwargs):
        nonlocal batch_calls
        batch_calls += 1
        count = int(re.search(r"Generate exactly (\d+)", prompt).group(1))
        return json.dumps([
            {
                "question_text": f"JavaScript {hashlib.sha256(f'{batch_calls}-{index}'.encode()).hexdigest()}",
                "options": ["A", "B", "C", "D"], "correct_option": index % 4,
                "explanation": "Generated by the Gemini test double.",
            }
            for index in range(count)
        ])

    monkeypatch.setattr(ai_engine, "_call_gemini_with_fallback", generated_gemini)
    async with engine.begin() as connection:
        await connection.run_sync(Base.metadata.create_all)
    try:
        async with session_factory() as db:
            assessment = await AssessmentService.create_assessment_session(
                db, None, topics=["JavaScript"], question_count=100, duration_minutes=180,
            )
            assert len(await AssessmentService.generate_questions_for_session(db, assessment.id)) == 100
            assert batch_calls == 10
    finally:
        await engine.dispose()
